version: '3.11'

services:
  flask_app:
    image: vasilis/flask_app
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgres://user:password@host:5432/database
    volumes:
      - ./:/app
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
